# Generated by Django 5.0.7 on 2026-07-20 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_hour', models.PositiveSmallIntegerField(default=7)),
                ('email_minute', models.PositiveSmallIntegerField(default=0)),
                ('last_emailed_on', models.DateField(blank=True, null=True)),
                ('health_profile', models.CharField(choices=[('general', 'General / no condition'), ('asthma', 'Asthma / respiratory condition'), ('heart', 'Cardiovascular condition'), ('athlete', 'Fitness enthusiast / runner'), ('child_elderly', 'Child or elderly household member')], default='general', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
