# Generated by Django 5.0.7 on 2026-07-20 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_label', models.CharField(max_length=120)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_label', models.CharField(max_length=120)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('travel_mode', models.CharField(choices=[('walking', 'Walking / Jogging'), ('bicycling', 'Cycling'), ('driving', 'Driving')], default='walking', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
